SET FEEDBACK ON;
SET DEFINE OFF;
SET LINESIZE 200;
SET PAGESIZE 100;


CREATE TABLE DMKHOA (
    MAKHOA  CHAR(2) PRIMARY KEY,
    TENKHOA NVARCHAR2(30)
);

CREATE TABLE DMMH (
    MAMH    CHAR(2) PRIMARY KEY,
    TENMH   NVARCHAR2(35),
    SOTIET  NUMBER(3)
);

CREATE TABLE DMSV (
    MASV      CHAR(3) PRIMARY KEY,
    HOSV      NVARCHAR2(30),
    TENSV     NVARCHAR2(10),
    PHAI      NVARCHAR2(3),
    NGAYSINH  DATE,
    NOISINH   NVARCHAR2(25),
    MAKH      CHAR(2),
    HOCBONG   NUMBER(10,0),
    CONSTRAINT FK_DMSV_DMKHOA FOREIGN KEY (MAKH) REFERENCES DMKHOA(MAKHOA)
);

-- Ghi chu: De bai ban gui phan KETQUA bi cat dong.
-- O day them cot DIEM NUMBER(4,2) theo cau truc quan ly diem thong dung.
CREATE TABLE KETQUA (
    MASV   CHAR(3),
    MAMH   CHAR(2),
    DIEM   NUMBER(4,2),
    PRIMARY KEY (MASV, MAMH),
    CONSTRAINT FK_KQ_DMSV FOREIGN KEY (MASV) REFERENCES DMSV(MASV),
    CONSTRAINT FK_KQ_DMMH FOREIGN KEY (MAMH) REFERENCES DMMH(MAMH)
);


INSERT INTO DMKHOA VALUES ('AV', 'Anh van');
INSERT INTO DMKHOA VALUES ('TH', 'Tin hoc');
INSERT INTO DMKHOA VALUES ('TR', 'Triet hoc');
INSERT INTO DMKHOA VALUES ('KT', 'Ke toan');
INSERT INTO DMKHOA VALUES ('SH', 'Sinh hoc');


INSERT INTO DMMH VALUES ('01', 'Co so du lieu', 45);
INSERT INTO DMMH VALUES ('02', 'Tri tue nhan tao', 45);
INSERT INTO DMMH VALUES ('03', 'Truyen tin', 45);
INSERT INTO DMMH VALUES ('04', 'Do hoa ung dung', 60);
INSERT INTO DMMH VALUES ('05', 'Van pham', 60);
INSERT INTO DMMH VALUES ('06', 'Ky thuat lap trinh', 45);


INSERT INTO DMSV VALUES ('A01', 'Nguyen Thi', 'Hai', 'Nu',  TO_DATE('23/02/1990', 'DD/MM/YYYY'), 'Ha Noi',      'TH', 130000);
INSERT INTO DMSV VALUES ('A02', 'Tran Van',   'Chinh', 'Nam', TO_DATE('24/12/1992', 'DD/MM/YYYY'), 'Binh Dinh',  'AV', 150000);
INSERT INTO DMSV VALUES ('A03', 'Le Thu',     'Yen', 'Nu',    TO_DATE('21/02/1990', 'DD/MM/YYYY'), 'TP HCM',     'TH', 170000);
INSERT INTO DMSV VALUES ('A04', 'Tran Anh',   'Tuan', 'Nam',  TO_DATE('20/12/1990', 'DD/MM/YYYY'), 'Ha Noi',     'AV', 80000);
INSERT INTO DMSV VALUES ('B01', 'Tran Thanh', 'Mai', 'Nu',    TO_DATE('12/08/1991', 'DD/MM/YYYY'), 'Hai Phong',  'TR', 0);
INSERT INTO DMSV VALUES ('B02', 'Nguyen Van', 'Nam', 'Nam',   TO_DATE('17/01/1990', 'DD/MM/YYYY'), 'Ben Tre',    'KT', 0);
INSERT INTO DMSV VALUES ('B03', 'Le Thi',     'Thao', 'Nu',   TO_DATE('13/01/1992', 'DD/MM/YYYY'), 'Da Nang',    'SH', 0);
INSERT INTO DMSV VALUES ('B04', 'Pham Quoc',  'Bao', 'Nam',   TO_DATE('25/03/1991', 'DD/MM/YYYY'), 'Dong Nai',   'TH', 0);


INSERT INTO KETQUA VALUES ('A01', '01', 8.5);
INSERT INTO KETQUA VALUES ('A01', '02', 7.0);
INSERT INTO KETQUA VALUES ('A01', '03', 9.0);
INSERT INTO KETQUA VALUES ('A02', '01', 6.5);
INSERT INTO KETQUA VALUES ('A02', '05', 8.0);
INSERT INTO KETQUA VALUES ('A03', '01', 9.0);
INSERT INTO KETQUA VALUES ('A03', '02', 8.5);
INSERT INTO KETQUA VALUES ('A03', '06', 7.5);
INSERT INTO KETQUA VALUES ('A04', '03', 6.0);
INSERT INTO KETQUA VALUES ('B01', '05', 7.5);
INSERT INTO KETQUA VALUES ('B01', '06', 6.5);
INSERT INTO KETQUA VALUES ('B02', '01', 5.5);
INSERT INTO KETQUA VALUES ('B02', '04', 7.0);
INSERT INTO KETQUA VALUES ('B03', '02', 8.0);
INSERT INTO KETQUA VALUES ('B03', '05', 7.0);
INSERT INTO KETQUA VALUES ('B04', '01', 6.0);
INSERT INTO KETQUA VALUES ('B04', '06', 8.5);

COMMIT;


