SET FEEDBACK ON;
SET DEFINE OFF;

-- 1. Bang PHONGBAN
CREATE TABLE PHONGBAN (
    MAPHG INT PRIMARY KEY,
    TENPHG NVARCHAR2(50),
    TRPHG CHAR(9),
    NG_NHANCHUC DATE
);

-- 2. Bang NHANVIEN
CREATE TABLE NHANVIEN (
    MANV CHAR(9) PRIMARY KEY,
    HONV NVARCHAR2(15),
    TENLOT NVARCHAR2(15),
    TENNV NVARCHAR2(15),
    NGSINH DATE,
    DCHI NVARCHAR2(50),
    PHAI NVARCHAR2(3),
    LUONG FLOAT,
    MA_NQL CHAR(9),
    PHG INT,
    CONSTRAINT FK_NV_NQL FOREIGN KEY (MA_NQL) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_NV_PHG FOREIGN KEY (PHG) REFERENCES PHONGBAN(MAPHG)
);
ALTER TABLE PHONGBAN
ADD CONSTRAINT FK_PHG_NV FOREIGN KEY (TRPHG) REFERENCES NHANVIEN(MANV);

-- 3. Bang DIADIEM_PHG
CREATE TABLE DIADIEM_PHG (
    MAPHG INT,
    DIADIEM NVARCHAR2(50),
    PRIMARY KEY (MAPHG, DIADIEM),
    CONSTRAINT FK_DDP_PHG FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)
);

-- 4. Bang DEAN
CREATE TABLE DEAN (
    MADA INT PRIMARY KEY,
    TENDA NVARCHAR2(50),
    DDIEM_DA NVARCHAR2(50),
    PHONG INT,
    CONSTRAINT FK_DA_PHG FOREIGN KEY (PHONG) REFERENCES PHONGBAN(MAPHG)
);

-- 5. Bang PHANCONG
CREATE TABLE PHANCONG (
    MA_NVIEN CHAR(9),
    SODA INT,
    THOIGIAN FLOAT,
    PRIMARY KEY (MA_NVIEN, SODA),
    CONSTRAINT FK_PC_NV FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_PC_DA FOREIGN KEY (SODA) REFERENCES DEAN(MADA)
);

-- 6. Bang THANNHAN
CREATE TABLE THANNHAN (
    MA_NVIEN CHAR(9),
    TENTN NVARCHAR2(50),
    PHAI NVARCHAR2(3),
    NGSINH DATE,
    QUANHE NVARCHAR2(20),
    PRIMARY KEY (MA_NVIEN, TENTN),
    CONSTRAINT FK_TN_NV FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV)
);


INSERT INTO PHONGBAN (MAPHG, TENPHG, TRPHG, NG_NHANCHUC)
VALUES (1, 'Quan ly', NULL, NULL);

INSERT INTO PHONGBAN (MAPHG, TENPHG, TRPHG, NG_NHANCHUC)
VALUES (4, 'Dieu hanh', NULL, NULL);

INSERT INTO PHONGBAN (MAPHG, TENPHG, TRPHG, NG_NHANCHUC)
VALUES (5, 'Nghien cuu', NULL, NULL);


INSERT INTO NHANVIEN (MANV, HONV, TENLOT, TENNV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES ('888665555', 'Le', 'Van', 'GiamDoc', TO_DATE('10/11/1937', 'DD/MM/YYYY'),
        '450 Stone, Houston, TX', 'Nam', 55000, NULL, 1);

INSERT INTO NHANVIEN (MANV, HONV, TENLOT, TENNV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES ('333445555', 'Nguyen', 'Thanh', 'Tung', TO_DATE('08/12/1945', 'DD/MM/YYYY'),
        '638 Voss, Houston, TX', 'Nam', 40000, '888665555', 5);

INSERT INTO NHANVIEN (MANV, HONV, TENLOT, TENNV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES ('987654321', 'Tran', 'Thi', 'Wallace', TO_DATE('20/06/1941', 'DD/MM/YYYY'),
        '291 Berry, Bellaire, TX', 'Nu', 43000, '888665555', 4);

INSERT INTO NHANVIEN (MANV, HONV, TENLOT, TENNV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES ('123456789', 'Dinh', 'Ba', 'Tien', TO_DATE('09/01/1965', 'DD/MM/YYYY'),
        '731 Fondren, Houston, TX', 'Nam', 30000, '333445555', 5);

INSERT INTO NHANVIEN (MANV, HONV, TENLOT, TENNV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES ('666884444', 'Do', 'Khanh', 'Nhan', TO_DATE('15/09/1962', 'DD/MM/YYYY'),
        '975 Fire Oak, Humble, TX', 'Nam', 38000, '333445555', 5);

INSERT INTO NHANVIEN (MANV, HONV, TENLOT, TENNV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES ('453453453', 'Pham', 'Anh', 'Thu', TO_DATE('31/07/1972', 'DD/MM/YYYY'),
        '5631 Rice, Houston, TX', 'Nu', 25000, '333445555', 5);

INSERT INTO NHANVIEN (MANV, HONV, TENLOT, TENNV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES ('999887777', 'Bui', 'Thuy', 'Vu', TO_DATE('19/07/1968', 'DD/MM/YYYY'),
        '3321 Castle, Spring, TX', 'Nu', 25000, '987654321', 4);

INSERT INTO NHANVIEN (MANV, HONV, TENLOT, TENNV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES ('987987987', 'Hoang', 'Van', 'Jabbar', TO_DATE('29/03/1969', 'DD/MM/YYYY'),
        '980 Dallas, Houston, TX', 'Nam', 25000, '987654321', 4);


UPDATE PHONGBAN
SET    TRPHG = '888665555',
       NG_NHANCHUC = TO_DATE('19/06/1971', 'DD/MM/YYYY')
WHERE  MAPHG = 1;

UPDATE PHONGBAN
SET    TRPHG = '987654321',
       NG_NHANCHUC = TO_DATE('01/01/1985', 'DD/MM/YYYY')
WHERE  MAPHG = 4;

UPDATE PHONGBAN
SET    TRPHG = '333445555',
       NG_NHANCHUC = TO_DATE('22/05/1978', 'DD/MM/YYYY')
WHERE  MAPHG = 5;


INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM) VALUES (1, 'Houston');
INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM) VALUES (4, 'Stafford');
INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM) VALUES (5, 'Bellaire');
INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM) VALUES (5, 'Sugarland');
INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM) VALUES (5, 'Houston');


INSERT INTO DEAN (MADA, TENDA, DDIEM_DA, PHONG)
VALUES (1, 'San pham X', 'Bellaire', 5);

INSERT INTO DEAN (MADA, TENDA, DDIEM_DA, PHONG)
VALUES (2, 'San pham Y', 'Sugarland', 5);

INSERT INTO DEAN (MADA, TENDA, DDIEM_DA, PHONG)
VALUES (3, 'San pham Z', 'Houston', 5);

INSERT INTO DEAN (MADA, TENDA, DDIEM_DA, PHONG)
VALUES (10, 'Tin hoc hoa', 'Stafford', 4);

INSERT INTO DEAN (MADA, TENDA, DDIEM_DA, PHONG)
VALUES (20, 'Tai to chuc', 'Houston', 1);

INSERT INTO DEAN (MADA, TENDA, DDIEM_DA, PHONG)
VALUES (30, 'Phuc loi moi', 'Stafford', 4);


INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('123456789', 1, 32.5);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('123456789', 2, 7.5);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('666884444', 3, 40.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('453453453', 1, 20.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('453453453', 2, 20.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('333445555', 2, 10.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('333445555', 3, 10.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('333445555', 10, 10.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('333445555', 20, 10.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('999887777', 30, 30.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('999887777', 10, 10.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('987987987', 10, 35.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('987987987', 30, 5.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('987654321', 30, 20.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('987654321', 20, 15.0);
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('888665555', 20, NULL);

INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
VALUES ('333445555', 'Alice', 'Nu', TO_DATE('05/04/1986', 'DD/MM/YYYY'), 'Con gai');

INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
VALUES ('333445555', 'Theodore', 'Nam', TO_DATE('25/10/1983', 'DD/MM/YYYY'), 'Con trai');

INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
VALUES ('333445555', 'Joy', 'Nu', TO_DATE('03/05/1958', 'DD/MM/YYYY'), 'Vo');

INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
VALUES ('987654321', 'Abner', 'Nam', TO_DATE('28/02/1942', 'DD/MM/YYYY'), 'Chong');

INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
VALUES ('123456789', 'Michael', 'Nam', TO_DATE('04/01/1988', 'DD/MM/YYYY'), 'Con trai');

INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
VALUES ('123456789', 'Alice', 'Nu', TO_DATE('30/12/1988', 'DD/MM/YYYY'), 'Con gai');

INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
VALUES ('123456789', 'Elizabeth', 'Nu', TO_DATE('05/05/1967', 'DD/MM/YYYY'), 'Vo');

COMMIT;